language: node_js
node_js:
  - "12"
jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=kai-al -Dsonar.projectKey=lab2-2022 -Dsonar.sources='./app' -X